name: CI
run-name: Pytest
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Installation dependencies
        run: python -m pip install pdm
      - run: pdm install
      - name: Running tests
        run: pytest
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Installation dependencies
        run: python -m pip install pdm
      - run: pdm install
      - name: Run Ruff
        run: ruff check .
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Installation dependencies
        run: python -m pip install pdm
      - run: pdm install
      - name: Type checks
        run: mypy ./src ./tests
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Installation dependencies
        run: python -m pip install pdm
      - run: pdm install
      - name: Type checks
        run: pyright ./src ./tests
